# Chart-related enumeration constants.
#
# Ported from python-pptx/src/pptx/enum/chart.py.


#' XL_CHART_TYPE — chart type enumeration
#'
#' Integer constants specifying chart types, mirroring XlChartType.
#'
#' @keywords internal
#' @export
XL_CHART_TYPE <- list(
  THREE_D_AREA                 =  -4098L,
  THREE_D_AREA_STACKED         =    78L,
  THREE_D_AREA_STACKED_100     =    79L,
  THREE_D_BAR_CLUSTERED        =    60L,
  THREE_D_BAR_STACKED          =    61L,
  THREE_D_BAR_STACKED_100      =    62L,
  THREE_D_COLUMN               = -4100L,
  THREE_D_COLUMN_CLUSTERED     =    54L,
  THREE_D_COLUMN_STACKED       =    55L,
  THREE_D_COLUMN_STACKED_100   =    56L,
  THREE_D_LINE                 = -4101L,
  THREE_D_PIE                  = -4102L,
  THREE_D_PIE_EXPLODED         =    70L,
  AREA                         =     1L,
  AREA_STACKED                 =    76L,
  AREA_STACKED_100             =    77L,
  BAR_CLUSTERED                =    57L,
  BAR_OF_PIE                   =    71L,
  BAR_STACKED                  =    58L,
  BAR_STACKED_100              =    59L,
  BUBBLE                       =    15L,
  BUBBLE_THREE_D_EFFECT        =    87L,
  COLUMN_CLUSTERED             =    51L,
  COLUMN_STACKED               =    52L,
  COLUMN_STACKED_100           =    53L,
  CONE_BAR_CLUSTERED           =   102L,
  CONE_BAR_STACKED             =   103L,
  CONE_BAR_STACKED_100         =   104L,
  CONE_COL                     =   105L,
  CONE_COL_CLUSTERED           =    99L,
  CONE_COL_STACKED             =   100L,
  CONE_COL_STACKED_100         =   101L,
  CYLINDER_BAR_CLUSTERED       =    95L,
  CYLINDER_BAR_STACKED         =    96L,
  CYLINDER_BAR_STACKED_100     =    97L,
  CYLINDER_COL                 =    98L,
  CYLINDER_COL_CLUSTERED       =    92L,
  CYLINDER_COL_STACKED         =    93L,
  CYLINDER_COL_STACKED_100     =    94L,
  DOUGHNUT                     = -4120L,
  DOUGHNUT_EXPLODED            =    80L,
  LINE                         =     4L,
  LINE_MARKERS                 =    65L,
  LINE_MARKERS_STACKED         =    66L,
  LINE_MARKERS_STACKED_100     =    67L,
  LINE_STACKED                 =    63L,
  LINE_STACKED_100             =    64L,
  PIE                          =     5L,
  PIE_EXPLODED                 =    69L,
  PIE_OF_PIE                   =    68L,
  PYRAMID_BAR_CLUSTERED        =   109L,
  PYRAMID_BAR_STACKED          =   110L,
  PYRAMID_BAR_STACKED_100      =   111L,
  PYRAMID_COL                  =   112L,
  PYRAMID_COL_CLUSTERED        =   106L,
  PYRAMID_COL_STACKED          =   107L,
  PYRAMID_COL_STACKED_100      =   108L,
  RADAR                        = -4151L,
  RADAR_FILLED                 =    82L,
  RADAR_MARKERS                =    81L,
  STOCK_HLC                    =    88L,
  STOCK_OHLC                   =    89L,
  STOCK_VHLC                   =    90L,
  STOCK_VOHLC                  =    91L,
  SURFACE                      =    83L,
  SURFACE_TOP_VIEW             =    85L,
  SURFACE_TOP_VIEW_WIREFRAME   =    86L,
  SURFACE_WIREFRAME            =    84L,
  XY_SCATTER                   = -4169L,
  XY_SCATTER_LINES             =    74L,
  XY_SCATTER_LINES_NO_MARKERS  =    75L,
  XY_SCATTER_SMOOTH            =    72L,
  XY_SCATTER_SMOOTH_NO_MARKERS =    73L
)
